apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: test
  name: test
spec:
  replicas: 6
  selector:
    matchLabels:
      run: test
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: test
    spec:
      containers:
      - image: nginx:1.14
        name: nginx

